name: Run client tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd client && npm install
    - name: Run tests
      run: npm test
